In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame


In [3]:
obj = pd.Series([4, 7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','a','c'])

In [9]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [10]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [11]:
np.exp(ojb2)

NameError: name 'np' is not defined

In [12]:
np.exp(obj2)

NameError: name 'np' is not defined

In [13]:
import numpy as np

In [14]:
np.exp(obj())

TypeError: 'Series' object is not callable

In [15]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
'e' in obj2

False

In [18]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [19]:
obj3 = pd.Series.(sdata)

SyntaxError: invalid syntax (<ipython-input-19-afa3d22b9bc2>, line 1)

In [20]:
obj3 = pd.Series(sdata)

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
states = ['California','Ohio','Oregon','Texas']

In [23]:
obj4 = pd.Series(sdata, index = states)

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
obj3 + obj 4

SyntaxError: invalid syntax (<ipython-input-30-6ab50f58ef4d>, line 1)

In [31]:
obj4.name = 'population'

In [32]:
obj4.index.name = 'state'

In [33]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [34]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [35]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [36]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [37]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [39]:
data = {'state':['Ohio', 'Ohio','Ohio', 'Nevada','Nevada','Nevada'],'year':[2000,2001,2002,2001,2002,2003],'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [40]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [41]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [43]:
pd.DataFrame(data, colunmns=['year','state','pop'])

TypeError: __init__() got an unexpected keyword argument 'colunmns'

In [44]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [48]:
frame2 = pd.DataFrame(data, columns = ['year','state','pop','debt'], index=['one','two','three','four','five','six'])

In [49]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [50]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [51]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [52]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [53]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [55]:
frame2['debt']=16.5

In [56]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [57]:
frame2['debt']= np.arange(6.)

In [58]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [66]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [67]:
frame2['debt']= val

In [70]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [76]:
frame2['eastern'] = frame2.state == 'Ohio'

In [78]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [79]:
del frame2['eastern']

In [80]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [81]:
pop = {'Nevada':{2001:2.4, 2002:2.9,},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [82]:
frame3 = pd.DataFrame(pop)

In [83]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [84]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [86]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [87]:
pdata = {'Ohio':frame3['Ohio'][:-1],'Nevada':frame3['Nevada'][:2]}

In [88]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [89]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [90]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [91]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [92]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [93]:
index = obj.index

In [94]:
index

Index(['a', 'b', 'c'], dtype='object')

In [95]:
index[1:]

Index(['b', 'c'], dtype='object')

In [96]:
labels = pd.Index(np.arange(3))

In [98]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [99]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [100]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [101]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [102]:
obj2.index is labels

True

In [103]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [104]:
 frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [105]:
'Ohio' in frame3.columns

True

In [106]:
2003 in frame3.index

False

In [107]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [108]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [109]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [110]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [111]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [112]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [113]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [114]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [115]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [116]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
     index=['a', 'c', 'd'],
     columns=['Ohio', 'Texas', 'California'])

In [117]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [118]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [119]:
frame2


Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [120]:
states = ['Texas', 'Utah', 'California']

In [121]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [122]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [123]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [124]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [125]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [126]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [127]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
....: index=['a', 'c', 'd'],
....: columns=['Ohio', 'Texas', 'California'])

In [128]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [129]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [130]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [131]:
states = ['Texas', 'Utah', 'California']

In [132]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [133]:
frame.loc[['a', 'b', 'c', 'd'], states]

c:\users\divya\appdata\local\programs\python\python36-32\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [134]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [135]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [136]:
new_obj = obj.drop('c')

In [137]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [138]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [139]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
     index=['Ohio', 'Colorado', 'Utah', 'New York'],
     columns=['one', 'two', 'three', 'four'])

In [140]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [141]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [142]:
data.drop(['Colorado', 'Ohio'])


one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [143]:
 data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [144]:
obj.drop('c',inplace=True)

In [145]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [146]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [147]:
 obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [148]:
obj['b']

1.0

In [149]:
obj[1]

1.0

In [150]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [151]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [152]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [153]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [154]:
 obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [155]:
obj['b':'c'] = 5

In [156]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [157]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
     index=['Ohio', 'Colorado', 'Utah', 'New York'],
     columns=['one', 'two', 'three', 'four'])

In [158]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [159]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [160]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [161]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [162]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [163]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [164]:
data[data < 5] = 0

In [165]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [166]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [167]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [168]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [169]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [170]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [171]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [174]:
ser = pd.Series(np.arange(3.))


In [175]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [176]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [177]:
ser2[-1]

2.0

In [178]:
ser[:1]

0    0.0
dtype: float64

In [179]:
ser.iloc[:1]

0    0.0
dtype: float64

In [180]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [181]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
     index=['a', 'c', 'e', 'f', 'g'])

In [182]:
s1


a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [183]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [184]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [185]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
     index=['Ohio', 'Texas', 'Colorado'])

In [186]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [187]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [188]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [189]:
 df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [190]:
df1 = pd.DataFrame({'A': [1, 2]})


In [191]:
df2 = pd.DataFrame({'B': [3, 4]})

In [192]:
df1

A
0  1
1  2

In [193]:
df2

B
0  3
1  4

In [194]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [195]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
     columns=list('abcd'))

In [196]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
    columns=list('abcde'))

In [197]:
df2.loc[1, 'b'] = np.nan

In [198]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [199]:
 df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [200]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [201]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [202]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [203]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [204]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [205]:
arr = np.arange(12.).reshape((3, 4))

In [206]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [207]:
arr[0]

array([0., 1., 2., 3.])

In [208]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [209]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
    columns=list('bde'),
    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [210]:
series = frame.iloc[0]

In [211]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [212]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [213]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [214]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [215]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [216]:
series3 = frame['d']

In [217]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [218]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [219]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [220]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [221]:
f = lambda x: x.max() - x.min()

In [222]:
frame.apply(f)

b    1.355022
d    4.041414
e    3.174750
dtype: float64

In [223]:
frame.apply(f, axis='columns')

Utah      2.460206
Ohio      2.747143
Texas     1.176244
Oregon    1.568928
dtype: float64

In [226]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [227]:
frame.apply(f)

b         d         e
min -0.681715 -2.738173 -0.502937
max  0.673307  1.303241  2.671813

In [228]:
format = lambda x: '%.2f' % x

In [229]:
frame.applymap(format)

b      d      e
Utah     0.21   0.77   2.67
Ohio    -0.68  -2.74   0.01
Texas    0.67  -0.36  -0.50
Oregon  -0.27   1.30   0.31

In [230]:
frame['e'].map(format)

Utah       2.67
Ohio       0.01
Texas     -0.50
Oregon     0.31
Name: e, dtype: object

In [231]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [232]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [233]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
     index=['three', 'one'],
     columns=['d', 'a', 'b', 'c'])

In [234]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [235]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [236]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
    [np.nan, np.nan], [0.75, -1.3]],
     index=['a', 'b', 'c', 'd'],
    columns=['one', 'two'])

In [237]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [238]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [239]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [240]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [241]:
df.idxmax()

one    b
two    d
dtype: object

In [242]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [243]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [244]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [245]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [246]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

ModuleNotFoundError: No module named 'pandas_datareader'

In [248]:
#CHAPTER 6

In [249]:
!cat examples/ex1.csv
a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

cat: examples/ex1.csv: No such file or directory


NameError: name 'a' is not defined